---
title: "Week 3 Work"
author: "Arin Vansomphone"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# load packages
library(readr)
library(tidyverse)
library(ggplot2)
library(tidymodels)
library(multilevelmod)
library(lme4)
library(jtools)
library(censored)

# load data
bloodpressure <- read_csv("bloodpressure.csv")
cvdoutcomes <- read_csv("cvdoutcomes.csv")
hba1c <- read_csv("hba1c.csv")
lipids <- read_csv("lipids.csv")
microvascularoutcomes <- read_csv("microvascularoutcomes.csv")
otherlabs <- read_csv("otherlabs.csv")
accordkey <- read_csv("accord_key.csv")
```

# Creating a Robust Longitudinal Model of hba1c
```{r}
# removing unnecessary columns from accordkey
accordkey <- accordkey %>%
  select(-c(trial_elig, network, arm))

# assembling covariates into one dataset
data <- inner_join(hba1c, lipids, 
                          by = c('MaskID' = 'MaskID', 'Visit' = 'Visit'))
data <- inner_join(data, bloodpressure, 
                          by = c('MaskID' = 'MaskID', 'Visit' = 'Visit'))
data <- inner_join(data, otherlabs, 
                          by = c('MaskID' = 'MaskID', 'Visit' = 'Visit'))
data <- inner_join(data, accordkey, 
                          by = c('MaskID' = 'MaskID'))

data <- data %>%
  filter(Visit != "EXIT") # remove exit observations
data[data == "BLR"] <- "00" # change baseline to 0 months
data$Visit <- gsub("F", "", data$Visit) # remove "F" at each visit entry
data$Visit <- as.numeric(data$Visit) # turn visit to numeric
```

### Visualizing the data
```{r}
data %>%
  filter(MaskID %in% c(100001, 100002, 100003, 100004, 100005, 100006)) %>%
  ggplot(aes(x = Visit, y = hba1c)) +
  geom_point() +
  geom_line() + 
  facet_wrap(~MaskID)
```

```{r}
# test random effect impact of MaskID
m0 <- lmer(hba1c ~ 1 + (1 | MaskID),
           data = data)

jtools::summ(m0)
```

```{r}
# creating lmer
m1 <- lmer(hba1c ~ . - MaskID + (1 | MaskID), # patient is random variable
           data = data)

summary(m1)
```

```{r}
plot(m1)
```

```{r}
# creating new subject for prediction
new_subject <- tibble(
  Visit = 0:84, 
  MaskID = 100001
)
```


# Creating a survival model
```{r}
# adding survival outcomes to dataset
cvdoutcomes <- cvdoutcomes %>%
  select(MaskID, fuyrs_po, censor_po)

data <- inner_join(data, cvdoutcomes, 
                          by = ('MaskID' = 'MaskID'))
```


```{r}
# splitting train and test
data_train <- data[-c(1:5),]
data_test <- data[1:5,]
```

```{r}
# creating survival model
cox_spec <- proportional_hazards(penalty = 0.123) %>%
  set_engine("glmnet")

f_fit <- fit(cox_spec,
             Surv(fuyrs_po, censor_po) ~ .,
             data = data_train)

f_fit
```

```{r}
# prediction
f_pred <- predict(f_fit, new_data = data_test,
                  type = "survival", time = seq(0, 20, 1))

f_pred <- f_pred %>%
  mutate(MaskID = factor(1:5)) %>%
  unnest(cols = .pred)

f_pred %>%
  ggplot(aes(x = .eval_time, y = .pred_survival, col = MaskID)) +
  geom_step()
```


